services:
    web:
        image: quay.io/dbrugger946/vite-weather-client:latest
        ports:
            - "3000:8080"
        depends_on:
            - weather-server
    weather-server:
        image: quay.io/dbrugger946/weather-server:latest
        ports:
            - "8888:8080"