# Build the client app container

FROM registry.access.redhat.com/ubi8/nodejs-20-minimal AS build 

USER 0

RUN microdnf install curl

WORKDIR /app

COPY package.json .

ARG BUILD_CONFIGURATION=Release

RUN npm install

COPY . .

RUN npm run build


# Serve the app using NGINX
FROM registry.redhat.io/rhel9/nginx-124

COPY --from=build /app/dist /opt/app-root/src
COPY nginx/nginx.conf /opt/app-root/etc/nginx.d
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]


