apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- files:
  - ./nginx-proxy.conf
  name: nginx-conf-cm
resources:
- ./client-deployment.yaml
- ./client-service.yaml
- ./client-edge-route.yaml