apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: nginx-conf-cm
  behavior: create
  files:
  - ./conf/nginx.conf
- name: nginx-default-cm
  behavior: create
  files:
  - ./conf/default.conf
  
resources:
- ./client-deployment-upstream.yaml
- ./client-service.yaml
- ./client-edge-route.yaml